### PR TITLE
Bugfix/i4 running rt for non existing de causes fatal error

### LINKED ISSUE #4: CreateDeltaPackage fails when retrieving DataExtensions
When running createDeltaPackage it sometimes causes to crash when it retrieves DataExtensions with fuel-soap.

Log:

info: Retrieving as Template: dataExtension
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Error: Invalid argument for the equals operator. Filter[0] cannot be null or empty.
    at /node_modules/mcdev/lib/metadataTypes/MetadataType.js:532:35
    at FuelSoap.<anonymous> (/node_modules/fuel-soap/lib/fuel-soap.js:131:6)
    at FuelSoap.<anonymous> (/node_modules/fuel-soap/lib/fuel-soap.js:603:5)
    at Parser.<anonymous> (/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:315:20)
    . . . . . . .

### PR DESCRIPTION
**Pull request by JoernBerkefeld**
# PR details

## What is the purpose of this pull request? (put an "X" next to an item)

- [ ] Documentation update
- [x] Bug fix
- [ ] New metadata support
- [ ] Enhanced metadata
- [ ] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

## What changes did you make? (Give an overview)

- refactoring & jsdoc enhancements
- configured github vsc extension
- fixes #4: handle missing target of retrieveAsTemplate gracefully and output readable error

## Is there anything you'd like reviewers to focus on?
--
...

### CODE REVIEW

File: lib/metadataTypes/MetadataType.js [hunk 1]
```diff
@@ -572,7 +590,12 @@ class MetadataType {
         let results = {};
         do {
             options.uri = this.paginate(options.uri, lastPage);
-            const response = await this.client.RestClient.get(options);
+            let response;
+            try {
+                response = await this.client.RestClient.get(options);
```
Comment (DougMidgley) [inline lib/metadataTypes/MetadataType.js:595]: if this actually fails, shouldnt it break something more than just logging?

File: lib/metadataTypes/DataExtension.js [hunk 2]
```diff
@@ -829,28 +829,22 @@ class DataExtension extends MetadataType {
...
-        const dataExtensionOptions = {
-            props: templateFields,
+        const options = {
             filter: {
                 leftOperand: 'Name',
                 operator: 'equals',
                 rightOperand: name,
             },
         };
-
```
Comment (DougMidgley) [inline lib/metadataTypes/DataExtension.js:841]: this is basically being moved to the generic code yes?

File: lib/metadataTypes/MetadataType.js (hunk 1 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/MetadataType.js:595]: well, yes, just not within fuel which isn't great at producing errors one can handle... like with soap, when the API does not return a result, it just ends on a fatal error

**Review by DougMidgley — APPROVED** [review]
