### PR TITLE
Bugfix/295 dataextension fields not properly formatted in retrieve-folder after de-create

### LINKED ISSUE #295: [BUG] dataExtension fields not properly formatted after de-CREATE
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

after UPDATE we re-retrieve fields to ensure the field list is properly sorted. afterwards we also apply the field-postRetrieveTasks.

during CREATE however, we take what was deployed (including fields only required for the API call) and save that directly into the retrieve folder without further processing

### Expected Behavior

fields are always run through field-postRetrieveTasks

### Steps To Reproduce

_No response_

### Version

3.1.3

### Environment

- OS:
- Node:
- npm:

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by JoernBerkefeld**
# PR details

## What is the purpose of this pull request? (put an "X" next to an item)

- [x] Bugfix

## What changes did you make? (Give an overview)

- fixes #295 

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] ESLint & Prettier are not outputting errors or warnings
- [x] README.md updated (if applicable)

### CODE REVIEW

File: lib/metadataTypes/DataExtension.js [hunk 1]
```diff
@@ -252,13 +252,19 @@ class DataExtension extends MetadataType {
                 const existingFields = DataExtension.oldFields[item[this.definition.nameField]];
                 if (item.Fields !== '' && existingFields) {
                     // TODO should be replaced by a manual sort using existingFields
-                    // ! this is inefficient because it triggers a new download of the fields during the saveResults() step
+                    // ! this is inefficient because it triggers a new download of the fields
```
Comment (DougMidgley) [inline lib/metadataTypes/DataExtension.js:255]: if we leave comments like this, can we consider adding either a task to fix later?

Comment (JoernBerkefeld) [reply lib/metadataTypes/DataExtension.js:255]: Fair point. Creating a task now
