### PR TITLE
Hotfix/3.0.3 ECONNRESET

### LINKED ISSUE #100: [BUG] Handle ECONNRESET during deployment via generic methods
**Describe the bug**
During uploads we currently get a lot of ECONNRESET errors, just like during retrieve. These are somewhat easy to handle as long as we rely on the generic client.SoapClient and client.RestClient methods in MetadataType.js but they become difficult when the old wrappers are used.

That's currently still the case for:
- [  ] Campaign
- [  ] Data Extension

But we are also calling those generic methods outside of MetadataType.js:
- [ ] Asset.js
- [ ] Automation
- [ ] DataExtract
- [ ] EventDefinition
- [ ] FileTransfer
- [ ] Folder
- [ ] ImportFile
- [ ] Role

**Expected behavior**
Use one central wrapper for all types and make sure it can handle options accordingly while keeping errors handled at the same time.

**Versions:**
- mcdev (mcdev --version): 3.0.2

### LINKED ISSUE #102: [BUG] attempt to deploy Synchronized DEs fails with bad message
**Describe the bug**

**To Reproduce**
1. prep DE deployment to child bu
2. deploy

**Expected behavior**
One should be warned that Synched DEs need to be created via *Content Builder* and cannot be deployed.

**Screenshots**
image

**Versions:**
- mcdev (mcdev --version): 3.0.2

### LINKED ISSUE #104: [BUG] shared folders are not properly filtered from deploys on child bus
**Describe the bug**
the code is looking at r_folder_Path but comparing with the value from r_folder_ContentType...

**Versions:**
- mcdev (mcdev --version): 3.0.2

### LINKED ISSUE #107: [TASK] rewrite folder to use generic retrieve/update/create
related to #100

### LINKED ISSUE #108: [TASK] proper SOAP error messages for CREATE and UPDATE

### LINKED ISSUE #110: [TASK] improve error message for missing dependencies
currently it always states:
image

... which is irritating when seen during a retrieve ;-) we reused the same methods here that were originally built for deploy only

### PR DESCRIPTION
**Pull request by JoernBerkefeld**
# PR details

## What is the purpose of this pull request? (put an "X" next to an item)

- [x] Bug fix

## What changes did you make? (Give an overview)

- fixes #100 Handle ECONNRESET errors across various types (incl. Data Extensions)
- fixes #102 block deployment attempt for synchronized Data Extensions with proper error message
- fixes #104 block deployment of shared data extensions on child BUs (existing solution broke somewhere down the line)
- closes #107 rewrite folder to use generic update/create to help with ECONNRESET issue
- closes #108 return full API error messages for create & update via SOAP
- closes #110 improve error message for missing dependencies

## Is there anything you'd like reviewers to focus on?
The *ECONNRESET* bugs should be gone now for *retrieve* & *deploy* across all types that are enabled by default.
...

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] ESLint & Prettier are not outputting errors or warnings
- [x] Documentation updated (if applicable)
- [x] Changelog updated

### CODE REVIEW

File: lib/metadataTypes/DataExtension.js [hunk 1]
```diff
@@ -255,35 +256,50 @@ class DataExtension extends MetadataType {
...
-            this.client.dataExtension(config).patch((error, response) => {
-                if (error) {
-                    Util.logger.error('- error updating dataExtension: ' + metadata.CustomerKey);
-                    resolve(error);
-                } else {
-                    Util.logger.info('- updated dataExtension: ' + metadata.CustomerKey);
-                    resolve(response);
-                }
-            });
+        // const existingFieldNames = Object.keys(fieldsObj).map((key) => fieldsObj[key].Name);
```
Comment (DougMidgley) [inline lib/metadataTypes/DataExtension.js:267]: commented?

File: lib/metadataTypes/DataExtension.js [hunk 2]
```diff
@@ -255,35 +256,50 @@ class DataExtension extends MetadataType {
...
+        // convert simple array into object.Array.object format to cope with how the XML body in the SOAP call needs to look like:
+        // <Fields>
+        //   <Field>
+        //     <CustomerKey>SubscriberKey</CustomerKey>
+        //      ..
+        //   </Field>
+        // </Fields>
+
+        metadata.Fields = { Field: metadata.Fields };
+        console.log(metadata, metadata.Fields);
```
Comment (DougMidgley) [inline lib/metadataTypes/DataExtension.js:300]: commented + console?

File: lib/metadataTypes/Folder.js [hunk 3]
```diff
@@ -13,16 +13,16 @@ class Folder extends MetadataType {
     /**
      * Retrieves metadata of metadata type into local filesystem. executes callback with retrieved metadata
      * @param {String} retrieveDir Directory where retrieved metadata directory will be saved
-     * @param {String[]} [overrideFields] Returns specified fields even if their retrieve definition is not set to true
+     * @param {String[]} [additionalFields] Returns specified fields even if their retrieve definition is not set to true
```
Comment (DougMidgley) [inline lib/metadataTypes/Folder.js:16]: what if you want less?

File: lib/metadataTypes/Folder.js [hunk 4]
```diff
@@ -258,39 +258,38 @@ class Folder extends MetadataType {
...
+                `${this.definition.type}-${metadata.ContentType}.create:: Cannot create Root Folder: ${metadata.Name}`
+            );
+            return {};
+        }
         const tempCustomerKey = metadata.CustomerKey;
         const path = metadata.Path;
-        this.removeNotCreateableFields(metadata);
-        return new Promise((resolve) => {
-            if (metadata.Parent && metadata.Parent.ID && metadata.Parent.ID === 0) {
+        let response;
```
Comment (DougMidgley) [inline lib/metadataTypes/Folder.js:270]: why declaring here?

File: lib/metadataTypes/Folder.js [hunk 5]
```diff
@@ -258,39 +258,38 @@ class Folder extends MetadataType {
...
      */
-    static create(metadata) {
+    static async create(metadata) {
+        if (metadata.Parent && metadata.Parent.ID && metadata.Parent.ID === 0) {
+            Util.logger.error(
+                `${this.definition.type}-${metadata.ContentType}.create:: Cannot create Root Folder: ${metadata.Name}`
+            );
+            return {};
+        }
         const tempCustomerKey = metadata.CustomerKey;
```
Comment (DougMidgley) [inline lib/metadataTypes/Folder.js:268]: maybe these need moving into the try catch block?

File: lib/metadataTypes/Folder.js [hunk 6]
```diff
@@ -299,30 +298,29 @@ class Folder extends MetadataType {
...
-                    response.body.Results[0].Object.CustomerKey = tempCustomerKey;
-                    delete response.body.Results[0].Object.$;
-                    Util.logger.info(`- updated folder: ${path}`);
-                    resolve(response);
-                }
-            });
-        });
+        const tempCustomerKey = metadata.CustomerKey;
+        const path = metadata.Path;
+        let response;
```
Comment (DougMidgley) [inline lib/metadataTypes/Folder.js:303]: ditto

File: lib/metadataTypes/Folder.js [hunk 7]
```diff
@@ -451,25 +449,28 @@ class Folder extends MetadataType {
...
-                // filtered out path as we need them to be stored locally, but do not want to try and retrieve
-                this.client.SoapClient.retrieve(
-                    'DataFolder',
-                    this.getFieldNamesToRetrieve(overrideFields).filter(
-                        (field) => !field.includes('Path')
-                    ),
-                    options,
-                    (ex, response) => (ex ? reject(ex) : resolve(response))
-                );
+            let response;
```
Comment (DougMidgley) [inline lib/metadataTypes/Folder.js:461]: ditto

File: lib/metadataTypes/Folder.js [hunk 8]
```diff
@@ -451,25 +449,28 @@ class Folder extends MetadataType {
 
     /**
      * Helper to retrieve the folders as promise
-     * @param {String[]} [overrideFields] Returns specified fields even if their retrieve definition is not set to true
+     * @param {String[]} [additionalFields] Returns specified fields even if their retrieve definition is not set to true
      * @param {Boolean} [queryAllAccounts] which queryAllAccounts setting to use
      * @returns {Promise<Object>} soap object
      */
-    static async retrieveHelper(overrideFields, queryAllAccounts) {
+    static async retrieveHelper(additionalFields, queryAllAccounts) {
```
Comment (DougMidgley) [inline lib/metadataTypes/Folder.js:456]: same thing

File: lib/metadataTypes/MetadataType.js [hunk 9]
```diff
@@ -403,31 +403,54 @@ class MetadataType {
...
+                    `- error creating ${this.definition.type} '${
+                        metadataEntry[this.definition.keyField]
+                    }': ${errorMsg}`
+                );
+            } else {
+                throw ex;
+            }
 
-            return null;
+            return {};
```
Comment (DougMidgley) [inline lib/metadataTypes/MetadataType.js:453]: why change this?

File: lib/metadataTypes/MetadataType.js [hunk 10]
```diff
@@ -468,31 +491,54 @@ class MetadataType {
...
+                    `- error updating ${this.definition.type} '${
+                        metadataEntry[this.definition.keyField]
+                    }': ${errorMsg}`
+                );
+            } else {
+                throw ex;
+            }
 
-            return null;
+            return {};
```
Comment (DougMidgley) [inline lib/metadataTypes/MetadataType.js:541]: sure?

**Review by DougMidgley — CHANGES_REQUESTED** [review]

File: lib/metadataTypes/DataExtension.js (hunk 1 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/DataExtension.js:267]: _cough_
let me remove that :)

File: lib/metadataTypes/DataExtension.js (hunk 2 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/DataExtension.js:300]: true. 

- [ ] remove console.log
- [ ] remove commented code

File: lib/metadataTypes/Folder.js (hunk 5 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/Folder.js:268]: what for? dont see how it could cause an error

File: lib/metadataTypes/Folder.js (hunk 6 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/Folder.js:303]: - [ ] turn `let` into `const` inside of try-catch

File: lib/metadataTypes/Folder.js (hunk 8 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/Folder.js:456]: see reply above

File: lib/metadataTypes/Folder.js (hunk 7 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/Folder.js:461]: here it makes sense to keep it as-is because `response` needs to be available outside the await (lines 462ff) because we use it on 476

File: lib/metadataTypes/MetadataType.js (hunk 9 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/MetadataType.js:453]: because the outside scripts try and test for returnValue.xyz and fail with an error if returnValue is null - instead of gracefully failing on not finding a value in xyz

File: lib/metadataTypes/MetadataType.js (hunk 10 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/MetadataType.js:541]: same as above. outside scripts actually failed badly with the null response - which we simply didn't see in the past when APIs worked more or less like a charm :D

File: lib/metadataTypes/Folder.js (hunk 3 above)
Comment (DougMidgley) [reply lib/metadataTypes/Folder.js:16]: fine for me :)

File: lib/metadataTypes/Folder.js (hunk 5 above)
Comment (DougMidgley) [reply lib/metadataTypes/Folder.js:268]: if they arent used outside, they should be inside.

Comment (JoernBerkefeld) [reply lib/metadataTypes/Folder.js]: path is used in the catch part.
but I removed tempCustomerKey - from my test just now it does not seem to be necessary anymore

File: docs/dist/documentation.md [hunk 11]
```diff
@@ -2242,10 +2242,10 @@ Provides default functionality that can be overwritten by child metadata type cl
     * [.update(metadata, [metadataBefore])](#MetadataType.update) ⇒ <code>void</code>
     * [.upsert(metadata, deployDir, [buObject])](#MetadataType.upsert) ⇒ <code>Promise.&lt;MetadataTypeMap&gt;</code>
     * [.createREST(metadataEntry, uri)](#MetadataType.createREST) ⇒ <code>Promise</code>
-    * [.createSOAP(metadataEntry)](#MetadataType.createSOAP) ⇒ <code>Promise</code>
+    * [.createSOAP(metadataEntry, [overrideType], [handleOutside])](#MetadataType.createSOAP) ⇒ <code>Promise</code>
```
Comment (DougMidgley) [inline docs/dist/documentation.md:2245]: strange thing here

File: lib/metadataTypes/MetadataType.js (hunk 9 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/MetadataType.js:453]: - [ ] return null when there is no result instead of empty object
