### PR TITLE
#565 + #567 improve folder caching & #566 cache global all subs & #579 keep lost lists

### LINKED ISSUE #565: [BUG] list-caching fails if folders are not a dependency of one of the retrieved types
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

thats because to identify a list fully, we want to get their path even during caching
image

### Expected Behavior

_No response_

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

4.1.12

### Environment

- OS:
- Node:
- npm:

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### LINKED ISSUE #566: [BUG] if dependent list is the global all subs it wont be found on child bus
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

relevant for any type that uses list as dependency

### Expected Behavior

_No response_

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

4.1.12

### Environment

- OS:
- Node:
- npm:

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### LINKED ISSUE #567: [BUG] dataExtension-caching also caches all non-DE folders
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image
all folders are downloaded for caching purposes. example run done by retrieving importFile activities

### Expected Behavior

image
with filter on dataExtension folders applied

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

4.1.12

### Environment

- OS:
- Node:
- npm:

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### LINKED ISSUE #579: [BUG] lists with broken folder links not saved
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if the list's folder cannot be found, the list is currently not saved to disk. this prevents users from debugging the issue or even from moving the list to a still existing folder.

### Expected Behavior

_No response_

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

4.1.12

### Environment

- OS:
- Node:
- npm:

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by JoernBerkefeld**
**tickets**
- closes #565 
- closes #566 
- closes #567 
- closes #579 

**dependencies**
- blocks pr #549
- blocks pr #562

### CODE REVIEW

File: lib/metadataTypes/List.js [hunk 1]
```diff
@@ -95,10 +176,10 @@ class List extends MetadataType {
             if (!parseForCache) {
                 delete metadata.Category;
             }
-            return metadata;
         } catch (ex) {
             Util.logger.warn(` - List ${metadata.ID}: '${metadata.CustomerKey}': ${ex.message}`);
         }
+        return metadata;
```
Comment (DougMidgley) [inline lib/metadataTypes/List.js:182]: intentional?

**Review by DougMidgley — CHANGES_REQUESTED** [review]

File: lib/metadataTypes/List.js (hunk 1 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/List.js:182]: yes. this is the one change for #579
