### PR TITLE
Bugfix/236 retrieve for more than 2500 records fails soap

### LINKED ISSUE #236: [BUG] retrieve for >2500 records fails (SOAP)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image

19:13:59.264 info: Retrieving: folder
19:14:07.445 info: - more than 3522 folders in Business Unit - loading next batch...
19:14:30.937 error: Retrieving folder failed: response.Results is not iterable (cannot read property undefined)
19:14:30.938 debug: response.Results is not iterable (cannot read property undefined) TypeError: response.Results is not iterable (cannot read property undefined)
    at Function.retrieveHelper (C:\Git\sfmc-devtools\lib\metadataTypes\Folder.js:460:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Function.retrieve (C:\Git\sfmc-devtools\lib\metadataTypes\Folder.js:22:33)
    at async Retriever.retrieve (C:\Git\sfmc-devtools\lib\Retriever.js:102:34)
    at async Function._retrieveBU (C:\Git\sfmc-devtools\lib\index.js:438:43)
    at async Function.retrieve (C:\Git\sfmc-devtools\lib\index.js:365:43)

### Expected Behavior

proper iteration over folders

### Version

develop-branch

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by JoernBerkefeld**
# PR details

## What is the purpose of this pull request? (put an "X" next to an item)

_Please delete options that are not relevant._

- [ ] Documentation update
- [x] Bug fix
- [ ] New metadata support
- [ ] Enhanced metadata
- [ ] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

## What changes did you make? (Give an overview)

fixes #236

## Is there anything you'd like reviewers to focus on?

...

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] ESLint & Prettier are not outputting errors or warnings
- [ ] README.md updated (if applicable)
- [ ] CHANGELOG.md updated
- [ ] ran `npm run docs` to update developer docs

### CODE REVIEW

File: lib/metadataTypes/Folder.js [hunk 1]
```diff
@@ -446,30 +446,15 @@ class Folder extends MetadataType {
...
-        } while (status === 'MoreDataAvailable');
-        return Results;
+        const response = await this.client.soap.retrieveBulk(
+            'DataFolder',
+            this.getFieldNamesToRetrieve(additionalFields).filter(
+                (field) => !field.includes('Path')
+            ),
+            options
+        );
+        console.log(Object.keys(response));
```
Comment (DougMidgley) [inline lib/metadataTypes/Folder.js:456]: nope

File: lib/metadataTypes/MetadataType.js [hunk 2]
```diff
@@ -566,32 +566,12 @@ class MetadataType {
...
-                    }s found in Business Unit - loading next batch...`
-                );
-                batchCounter++;
-            }
-            const metadataBatch = this.parseResponseBody(resultsBatch);
-
-            metadata = { ...metadata, ...metadataBatch };
-        } while (status === 'MoreDataAvailable');
-
+        const metadata = await this.client.soap.retrieveBulk(
```
Comment (DougMidgley) [inline lib/metadataTypes/MetadataType.js:570]: can you return the promise directly?

**Review by DougMidgley — CHANGES_REQUESTED** [review]

File: lib/metadataTypes/MetadataType.js (hunk 2 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/MetadataType.js:570]: good point

File: lib/metadataTypes/Folder.js (hunk 1 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/Folder.js:456]: ok

File: lib/metadataTypes/MetadataType.js (hunk 2 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/MetadataType.js:570]: i can do you one better and remove retrieveSOAPBody() all together

File: lib/metadataTypes/MetadataType.js [hunk 3]
```diff
@@ -534,16 +534,21 @@ class MetadataType {
...
      */
-    static async retrieveSOAPgeneric(
+    static async retrieveSOAP(
         retrieveDir,
         buObject,
         requestParams,
         additionalFields,
         overrideType
     ) {
+        requestParams = requestParams || {};
```
Comment (DougMidgley) [inline lib/metadataTypes/MetadataType.js:544]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters
default potential?

Comment (JoernBerkefeld) [reply lib/metadataTypes/MetadataType.js:544]: nope, because any given value would override it. we could define a single "thats ok too" value but what if null, undefined or empty string is passed in? all those eval to false and hence would trigger going into the alternative empty object

**Review by DougMidgley — APPROVED** [review]
