### PR TITLE
Bug/2337 journey created date is incorrect in update response

### LINKED ISSUE #2337: [BUG] journey createdDate incorrect in update-response
basically, we should override the response from the update-response for the field `createdDate` with what was returned while caching the journeys. otherwise it looks like this:

Image

### PR DESCRIPTION
**Pull request by yuliialikhyt**
# PR details

## What changes did you make? (Give an overview)

Updated the createdDate in the journey with the cached value in post deploy. 

- closes #2337

## Further details (optional)

...

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] test scripts updated
- [ ] Wiki updated (if applicable)

### CODE REVIEW

File: lib/metadataTypes/Journey.js [hunk 1]
```diff
@@ -1880,6 +1880,10 @@ class Journey extends MetadataType {
      * @param {MetadataTypeMap} upsertResults metadata mapped by their keyField as returned by update/create
      */
     static async postDeployTasks(upsertResults) {
+        // override the response from update by createdDate from cache (the date from update-response is incorrect)
+        for (const [key, journey] of Object.entries(upsertResults)) {
+            journey.createdDate = cache.getByKey(this.definition.type, key)?.createdDate;
```
Comment (JoernBerkefeld) [inline lib/metadataTypes/Journey.js]: That doesn't seem to check if there is a match in the cache and consequently resets this to empty on newly created entries.

Comment (yuliialikhyt) [reply lib/metadataTypes/Journey.js]: Updated
