### PR TITLE
#213 ensure docs/roles file is not overwritten during role deploy

### LINKED ISSUE #213: [BUG] deploy `role` overwrites docs/roles file
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when you deploy 1 or multiple roles, the generic deploy method runs document for any types specified in the config. however, while that's good for multi-file documentation, it breaks for `role` (and probably `accountUser` as well), which gets documented into a single MD file per instance, rather than one MD file per record.

image

### Expected Behavior

deploy executes document only for multi-file documentation types 

### Steps To Reproduce

1. deploy one role
2. check the corresponding docs/roles/*.md file for your instance / credential file

### Version

3.1.3

### Environment

- OS:
- Node:
- npm:

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by JoernBerkefeld**
# PR details

## What is the purpose of this pull request? (put an "X" next to an item)

- [x] Bug fix

## What changes did you make? (Give an overview)

fix #213  

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] ESLint & Prettier are not outputting errors or warnings
- [-] README.md updated (if applicable)
- [n/a] CHANGELOG.md updated
- [n/a] ran `npm run docs` to update developer docs

### CODE REVIEW

File: lib/metadataTypes/definitions/Role.definition.js [hunk 1]
```diff
@@ -13,6 +13,7 @@ module.exports = {
         'SYS_DEF_SECURITYADMIN',
         'SYS_DEF_VIEWER',
     ],
+    documentInOneFile: true,
```
Comment (DougMidgley) [inline lib/metadataTypes/definitions/Role.definition.js:16]: I don't 100% agree with this approach. I actually wanna see document removed from deploy or retrieve. It should be its own thing. Then at CLI level it can be called after if need be on either. It will make the retrieve and deploy more "componentized", not to mention it would probably avoid the need for this modification since it would just take whatever is in the retrieve dir (which should be updated by whatever came from deploy)

**Review by DougMidgley — CHANGES_REQUESTED** [review]

File: lib/metadataTypes/definitions/Role.definition.js (hunk 1 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/definitions/Role.definition.js:16]: true - assuming the auto-documentation is a problem. 
on the other hand we used to see updates to our retrieve folder as a feature. and docs are created based on the retrieve folder. by disabling this we lead to difference between whats in retrieve and whats in docs.

it's 2 lines of code that can help us move forward with a fix of existing functionality instead of changing it.


I haven't seen a ticket nor a discussion prior to this bugfix about this, buddy. 
If we want to reduce whats done to docs/retrieve, we can add a new ticket for that and handle it as a feature change.

**Disputing a bugfix over a functional discussion seems wrong though.**

**Review by DougMidgley — APPROVED** [review]
