### PR TITLE
#320: Test Methods inverted and fixed

### LINKED ISSUE #320: [BUG] Tests Inverted in some cases
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running tests, some assertions are inverted (Actual <> Expected). This causes some interesting outcomes

### Expected Behavior

Assertions should be actual, then expected

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

develop-branch

### Environment

- OS:
- Node:
- npm:

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by DougMidgley**
# PR details

## What is the purpose of this pull request? (put an "X" next to an item)

_Please delete options that are not relevant._

- [ ] Documentation update
- [X] Bug fix
- [ ] New metadata support
- [ ] Enhanced metadata
- [ ] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

## What changes did you make? (Give an overview)

moved all file writing to await because otherwise the order of execution was wrong. This was hidden from tests when tests were expected THEN actual, but it should be actual THEN expected.  - closes #320 

## Is there anything you'd like reviewers to focus on?

general review

## Checklist

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] ESLint & Prettier are not outputting errors or warnings
- [X] README.md updated (if applicable)
- [X] CHANGELOG.md updated
- [X] ran `npm run docs` to update developer docs

### CODE REVIEW

File: lib/Retriever.js [hunk 1]
```diff
@@ -105,7 +105,6 @@ class Retriever {
                     if (templateVariables && Array.isArray(result)) {
                         // so far we are only doing this for templates, hence the above if-check
                         cache.setMetadata(
-                            this.buObject.mid,
```
Comment (DougMidgley) [inline lib/Retriever.js:108]: this is not the signature of the method, unsure why it was ever set like this

File: test/resources/9999999/query/build-expected.json [hunk 2]
```diff
@@ -1,11 +1,8 @@
 {
     "name": "testExistingQuery",
     "key": "testExistingQuery",
-    "description": "updated",
+    "description": "",
```
Comment (DougMidgley) [inline test/resources/9999999/query/build-expected.json:4]: seems our expected file was wrong

**Review by JoernBerkefeld — APPROVED** [review]
