### PR TITLE
Bugfix/187 mcdev bdb fails to find template where name and key differ

### LINKED ISSUE #187: [BUG] mcdev bdb fails to find template where name and key differ
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when trying to build a definition from a template, the process will look for a name, not a key.

### Expected Behavior

the logic should look for the key, as this is the value which stored by default as the filename

### Steps To Reproduce

22:19:56.607 debug: :: mcdev 3.1.0 ::
22:19:57.528 info: mcdev:: Build Definition from Template Bulk
22:19:57.530 info: Executing for 'training/MCDEV_Training_Target_1': 'QA'
22:19:57.531 info: mcdev:: Build Definition from Template
22:19:57.555 error: mcdev.buildDefinition:automation:: Could not find ./template\automation\Barcelona Automation.automation-meta.json.
22:19:57.555 debug: Error: automation:: Could not find ./template\automation\Barcelona Automation.automation-meta.json.
    at Function.buildDefinition (C:\Users\douglas.midgley\AppData\Roaming\npm\node_modules\mcdev\lib\metadataTypes\MetadataType.js:1273:23)
    at async Promise.all (index 0)
    at async Builder.buildDefinition (C:\Users\douglas.midgley\AppData\Roaming\npm\node_modules\mcdev\lib\Builder.js:69:28)

### Version

3.1.2

### Environment

- OS:
- Node:
- npm:

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by JoernBerkefeld**
# PR details

## What is the purpose of this pull request? (put an "X" next to an item)

- [x] Bugfix

## What changes did you make? (Give an overview)

**high priority bugfix for client demo!** 
- fixes #187 

inside of `createDeltaPkg` after running `retrieveAsTemplate` we gather the keys for the new templates and hand them over to `buildDefinitionBuild`. Before, both methods tried using the same value which had to be the name because that's what `rt` needed.

## Is there anything you'd like reviewers to focus on?

I moved the JSDoc definition from MetadataType.js to Util.js, enabling us to do what we talked about the other day but then couldn't. 

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] ESLint & Prettier are not outputting errors or warnings
- [ ] README.md updated (if applicable)
- [ ] CHANGELOG.md updated
- [x] ran `npm run docs` to update developer docs

### CODE REVIEW

File: lib/metadataTypes/Automation.js [hunk 1]
```diff
@@ -192,7 +192,7 @@ class Automation extends MetadataType {
         });
         if (results && Array.isArray(results.Results)) {
             // eq-operator returns a similar, not exact match and hence might return more than 1 entry
-            const [metadata] = results.filter((item) => item.Name === name);
+            const [metadata] = results.Results.filter((item) => item.Name === name);
```
Comment (DougMidgley) [inline lib/metadataTypes/Automation.js:195]: maybe DOUBLE check this, i know the move to sfmc-sdk sometimes changed this. it means it isnt in prod :P

**Review by DougMidgley — CHANGES_REQUESTED** [review]

File: lib/metadataTypes/Automation.js (hunk 1 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/Automation.js:195]: i branched from develop. tested with the develop version to confirm this
