### PR TITLE
Bugfix/628 journey builder triggeredsend not retrieved

### LINKED ISSUE #628: [BUG] journey builder triggeredSend not retrieved
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

we currently filter these entries with custom code.

### Expected Behavior

filtering should be done via the central filter option if needed. custom filters need to be removed

### Steps To Reproduce

3. Run '...'
4. See error...

### Version

4.2.0

### Environment

- OS:
- Node:
- npm:

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by JoernBerkefeld**
# PR details

## What changes did you make? (Give an overview)

- fixes #628 

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] test scripts updated
- [ ] Wiki updated (if applicable)

### CODE REVIEW

File: lib/metadataTypes/TriggeredSendDefinition.js [hunk 1]
```diff
@@ -137,7 +123,11 @@ class TriggeredSendDefinition extends MetadataType {
         // remove IsPlatformObject, always has to be 'false'
         delete metadata.IsPlatformObject;
         // folder
-        super.setFolderPath(metadata);
+        try {
+            this.setFolderPath(metadata);
+        } catch {
+            return;
```
Comment (DougMidgley) [inline lib/metadataTypes/TriggeredSendDefinition.js:129]: any reason to change this logic? are we just ignoring errors here?

Comment (JoernBerkefeld) [reply lib/metadataTypes/TriggeredSendDefinition.js:129]: yes. reason is rather simple. by removing the filter on IsPlatformObject we get journey builder TSDs, but we also get shit ton of deleted & hidden stuff that is no longer visible in the GUI.
the CLI was flooded by warnings before I changed that to simply skip these entries.

ideal? no. it's really just a workaround for yet another quirk in SFMC :(

Comment (JoernBerkefeld) [reply lib/metadataTypes/TriggeredSendDefinition.js:129]: i should add that thats also the reason why I changed the other Util.loggers in this method from WARN to VERBOSE. These other 2 cases occur less often and one should be able to see it at least in the logs because those other entries do show up in the GUI. without a folder though, one couldn't see them anywhere anyways.
