### PR TITLE
#214 ensure that errors in preDeployTasks are handled gracefully

### LINKED ISSUE #214: [BUG] missing deps for `fileTransfer` not processed correctly during deploy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image

### Expected Behavior

it should read

error: fileTransfer.upsert: s3test - Missing one or more dependent metadata. ftpLocation with name='**ExactTarget Enhanced FTP**' was not found on your BU
info: fileTransfer upsert: **0 of 1** created / 0 of 0 updated

mistakes:
1. ftpLocation name not properly displayed in error message
2. the CLI output incorrectly states that the fileTransfer was created
3. the success counter say 1 of 1 created instead of 0 of 1

### Steps To Reproduce

1. deploy a fileTransfer from one BU to another where the corresponding ftpLocation is not set up

### Version

3.1.3

### Environment

- OS:
- Node:
- npm:

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by JoernBerkefeld**
# PR details

## What is the purpose of this pull request? (put an "X" next to an item)

- [x] Bug fix

## What changes did you make? (Give an overview)

fix #214 

the total counter for created / updated used to not include records for which errors happened during preDeploySteps but now they do. This required updates to multiple other types than just the initially included fileTransfers

## Is there anything you'd like reviewers to focus on?

...

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] ESLint & Prettier are not outputting errors or warnings
- [n/a] README.md updated (if applicable)
- [n/a] CHANGELOG.md updated
- [x] ran `npm run docs` to update developer docs

### CODE REVIEW

File: lib/metadataTypes/MetadataType.js [hunk 1]
```diff
@@ -287,29 +300,42 @@ class MetadataType {
                             'Hotfix for non-cachable resource found in deploy folder. Trying update:'
                         );
                         Util.logger.warn(JSON.stringify(metadata[metadataKey]));
-                        metadataToUpdate.push({
-                            before: {},
-                            after: metadata[metadataKey],
-                        });
+                        if (error) {
+                            metadataToUpdate.push(null);
```
Comment (DougMidgley) [inline lib/metadataTypes/MetadataType.js:304]: why would we push null?

File: lib/metadataTypes/MetadataType.js [hunk 2]
```diff
@@ -287,29 +300,42 @@ class MetadataType {
...
                             this.definition.type,
                             normalizedKey
                         )[this.definition.idField];
-                        metadataToUpdate.push({
-                            before: cache.getByKey(this.definition.type, normalizedKey),
-                            after: metadata[metadataKey],
-                        });
+                        if (error) {
+                            // do this in case something went wrong during pre-deploy steps to ensure the total counter is correct
+                            metadataToUpdate.push(null);
```
Comment (DougMidgley) [inline lib/metadataTypes/MetadataType.js:319]: so if we are keeping count, we should put another var above the for loop, not putting in null.

File: lib/metadataTypes/MetadataType.js [hunk 3]
```diff
@@ -361,6 +387,9 @@ class MetadataType {
      * @returns {Promise} Promise
      */
     static async createREST(metadataEntry, uri) {
+        if (metadataEntry === null || metadataEntry === undefined) {
```
Comment (DougMidgley) [inline lib/metadataTypes/MetadataType.js:390]: same comment, what should we check here for?

**Review by DougMidgley — CHANGES_REQUESTED** [review]

File: lib/metadataTypes/FileTransfer.js [hunk 4]
```diff
@@ -110,21 +110,27 @@ class FileTransfer extends MetadataType {
...
+        if (metadata.r__ftpLocation_name) {
+            metadata.fileTransferLocationId = cache.searchForField(
+                'ftpLocation',
+                metadata.r__ftpLocation_name,
+                'name',
+                'id'
+            );
+        } else {
+            throw new Error(
+                'r__ftpLocation_name not set. Please ensure the source is properly set up and re-retrieve it first.'
```
[the remark this answers is not in the document]
Comment (JoernBerkefeld) [reply lib/metadataTypes/FileTransfer.js:126]: yes - that is the original case in the associated bug

File: lib/metadataTypes/MetadataType.js (hunk 1 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/MetadataType.js:304]: described in the PR text:
to update the "the total counter for created / updated "
I wanna see 0 of 1 instead of 0 of 0 there.

File: lib/metadataTypes/MetadataType.js (hunk 2 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/MetadataType.js:319]: why not?

File: lib/metadataTypes/Folder.js [hunk 5]
```diff
@@ -251,23 +251,26 @@ class Folder extends MetadataType {
...
     /**
      * creates a folder based on metatadata
-     * @param {Object} metadata metadata of the folder
+     * @param {Util.MetadataTypeItem} metadataEntry metadata of the folder
      * @returns {Promise} Promise
      */
-    static async create(metadata) {
-        if (metadata?.Parent?.ID === 0) {
+    static async create(metadataEntry) {
+        if (metadataEntry === null || metadataEntry === undefined) {
```
[the remark this answers is not in the document]
Comment (JoernBerkefeld) [reply lib/metadataTypes/Folder.js:258]: the nulls we pushed in or that resulted from the preDeployTask()

File: lib/metadataTypes/MetadataType.js (hunk 2 above)
Comment (JoernBerkefeld) [reply lib/metadataTypes/MetadataType.js:319]: we would need to additional variables to count updates and creates in parallel. simply pushing null makes it a lot cleaner

**Review by DougMidgley — APPROVED** [review]
